version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tu_password
      POSTGRES_DB: banco_db
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: api_banco_app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # Aqu√≠ ocurre la magia: 'db' es el nombre del servicio de arriba
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/banco_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tu_password